${TARGET}.axf: _frame0.o
${TARGET}.axf: _demarrage.o
${TARGET}.axf: _ConfigModule.o
${TARGET}.axf: _ConfigCapteur.o
${TARGET}.axf: _Alerte.o
${TARGET}.axf: _Etalonnage.o
${TARGET}.axf: _Seuillage.o
${TARGET}.axf: _MsgErreur.o
${TARGET}.axf: _SeuilUn.o
${TARGET}.axf: _Affichage.o
${TARGET}.axf: _Clavier.o
${TARGET}.axf: _PavetNum.o
${TARGET}.axf: _dict.o
${TARGET}.axf: ladder.o
${TARGET}.axf: imagedata.o
${TARGET}.axf: ladder_test_ldx.o
${TARGET}.axf: ${ROOT}/lib/VPD-133/startup_gcc.o
${TARGET}.axf: ${ROOT}/lib/commonlo.a
${TARGET}.axf: ${ROOT}/lib/libgr.a
${TARGET}.axf: ${ROOT}/lib/fonts.a
${TARGET}.axf: ${ROOT}/lib/font_icpdas_cs_cyrillic.a
${TARGET}.axf: ${ROOT}/lib/font_icpdas_cs_french.a
${TARGET}.axf: ${ROOT}/lib/font_icpdas_cs_latin1s.a
${TARGET}.axf: ${ROOT}/lib/font_icpdas_rc_cyrillic.a
${TARGET}.axf: ${ROOT}/lib/font_icpdas_rc_french.a
${TARGET}.axf: ${ROOT}/lib/font_icpdas_rc_latin1s.a
${TARGET}.axf: ${ROOT}/lib/VPD-133.a
${TARGET}.axf: ${ROOT}/lib/libdriver.a
